config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :messages
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true

  def show_last_message
    if(last_message = messages.last).present?
      if last_message.body?
        last_message.body
      else
        "画像が投稿されています"
      end
    else
      "メッサージがありません"
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, AvatarUploader

  validates :body_or_image, presence: true

  private
    def body_or_image
      body.presence or image.presence
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only:[:edit,:update]

  def index
  end

  def new
    @group = Group.new
    @users = @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @users = @group.users
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages= @group.messages.includes(:user)
    @new_messages = @group.messages.where("id > ?", params[:message_id])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body,:image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where("name like ?","%#{ params[:keyword] }%").where.not(id: current_user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json
      end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
   def user_params
    params.require(:user).permit(:name, :email)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name,"グループ名", class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label{class: "chat-group-form__label", for: "chat_group_チャットメンバーを追加"}チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input{class: 'chat-group-form__input', id: 'user-search-field', placeholder: '追加したいユーザー名を入力してください'}

      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right

      #chat-group-users
        #chat-group-user-8.chat-group-user.clearfix.js-chat-member
          %p.chat-group-user__name
          - if @users.present?
            - @users.each do |user|
              %input{name: 'group[user_ids][]', type: 'hidden', value: user.id, class: 'chat-group-user_id'}
              = user.name

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ!!
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_group.html.haml
%h2 #{group_name}
%p  #{message}

app/views/messages/_message.html.haml
.chat__content1__parent{"data-message-id": message.id}
  %h2.chat__content1__name
    = message.user.name
  %p.chat__content1__date
    = message.created_at.to_s(:datetime)

  - if message.body.present?
    .chat__content1__message
      = message.body
    .chat__content1__image
      = image_tag message.image.url if message.image.present?

app/views/messages/index.html.haml
%header
  %p チャットグループが作成されました
%nav
  .nav__user
    %ul
      %li.ul__name
        = current_user.name
      - if user_signed_in?
        %li.ul__edit
          = link_to new_group_path, class: "ul__edit__link", method: :get do
            =fa_icon "edit"
        %li.ul__cog
          = link_to edit_user_path(current_user), class: "ul__cog__link", method: :get do
            =fa_icon "cog"

  .nav__group
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        %h2
          = group.name
        %p
          = group.show_last_message
.chat
  .chat__header
    %h2
      = @group.name
    %p
      - @group.users.each do |user|
        =user.name

    = link_to edit_group_path(@group) do
      .edit
        edit

  .chat__content
    = render @messages
  .chat__fotter
    = form_for [@group, @message] do |f|
      = f.text_field :body, class: 'chat__fotter__text', placeholder: 'type a message'
      = f.label :image do
        %span.chat__fotter__icon
          =fa_icon "image"
        = f.file_field :image, class: 'chat__fotter__filesend'
      = f.submit 'Send', class: 'chat__fotter__submit'

app/views/shared/_side_bar.html.haml
%nav
  .nav__user
    %ul
      %li.ul__name
        = current_user.name
      - if user_signed_in?
        %li.ul__edit
          = link_to new_group_path, class: "ul__edit__link", method: :get do
            =fa_icon "edit"
        %li.ul__cog
          = link_to edit_user_path(current_user), class: "ul__cog__link", method: :get do
            =fa_icon "cog"
      - else
        %li.ul__edit
          = link_to 'https://qiita.com/knt45/items/c76b246ad448f3814ae4', class: "ul__edit__link", method: :get do
            = fa_icon "edit"
        %li.ul__cog
          = link_to new_user_registration, class: "ul__cog__link", method: :get do
            =fa_icon "cog"

  .nav__group
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        %h2
          = group.name
        %p
          メッセージはまだありません

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Edit Account", class: 'btn'